Add step configuration to specify match order
dapr/mechanical-markdown pull request #29
Opened 2022-09-30 16:12 UTC by shubham1172

This PR introduces a new step configuration: `match_order`.

If `match_order` is `sequential`, the expected lines are expected to be a part of output **in the same order**. This is the existing behavior and also the default (i.e. if `match_option` is missing).

If `match_order` is `none`, the expected lines can be **in any order** in the output.

Closes #18

2022-09-30 17:12 UTC, mukundansundar approved these changes
Lgtm

@berndverst thoughts?

2022-09-30 17:14 UTC, shubham1172 commented
FYI, I moved to Python 3.8 to use the walrus operator `:=`.

2022-09-30 17:42 UTC, berndverst commented
Python 3.7 is still supported and we run Python 3.7 tests with mechanical markdown in the Python SDK. You must retain Python 3.7 support.

2022-09-30 17:51 UTC, shubham1172 commented
> Python 3.7 is still supported and we run Python 3.7 tests with mechanical markdown in the Python SDK. You must retain Python 3.7 support.

Thanks, reverted back.

2022-10-04 20:17 UTC, berndverst commented on mechanical_markdown/__init__.py
> +__version__ = '0.5.3'
Let's version this as 0.6.0. This is major enough!

```suggestion
__version__ = '0.6.0'
```

2022-10-04 20:27 UTC, berndverst requested changes
The `examples` folder markdown itself is an integration test that uses mechanical markdown.

Please add a section to `https://github.com/dapr/mechanical-markdown/tree/main/examples/README.md` which shows how to use the new option, and which actually has the mechanical markdown annotation.

For this example, please do the following:
- Use Match Order `None`
- Assert expected output lines to be:
```
- "first"
- "second"
```

But in your example code block do:
```bash
echo "second"
echo "first"
```

This integration test should pass and also function as an example!

2022-10-05 06:09 UTC, shubham1172 commented
Somehow the build action is not getting triggered, but I validated the example locally - 
`python3 -m mechanical_markdown ./examples/io.md`

![image](https://user-images.githubusercontent.com/22132944/193992581-806ebac9-61c3-46c3-a952-8d570578fdd7.png)

2022-10-05 06:17 UTC, berndverst approved these changes
Thanks for adding the example and integration test! LGTM

2022-10-05 06:22 UTC, berndverst commented
@shubham1172 i can see this test ran part of CI/CD. It's the "examples" step as part of the build workflow. The third run on this PR seems to include it.

2022-10-05 06:23 UTC, berndverst commented
@artursouza please merge with STC power, unless @wcs1only wants to merge and happens to see this :)

2022-10-05 20:17 UTC, artursouza approved these changes

2022-10-05 20:17 UTC, merged