[WIP] Fix build pipeline
dapr/mechanical-markdown pull request #35
Opened 2023-06-12 19:11 UTC by shubham1172

2023-06-12 20:10 UTC, paulyuk approved these changes

2023-06-12 20:10 UTC, paulyuk commented on tests/test_link_validation.py
this is the key to get builds going I believe.  We'll want to come back normal hours for a complete fix.

2023-06-13 03:39 UTC, artursouza requested changes
Let's avoid removing the tests.

2023-06-13 03:46 UTC, shubham1172 commented
> Let's avoid removing the tests.

Needs further investigation on what is causing the FakeHttpServer to hang in tests. It works fine locally, but gets stuck in CI.
The tests are limited to link validations which is fairly easy to test manually for now. However it's not a great practice to remove tests, so I am ok blocking this until we find a fix.


To unblock quickstarts, we can then pin to mm 0.6.0 and mistune 2.0.1.

2023-06-13 04:35 UTC, artursouza commented
I found the issue. Let's see this run.

2023-06-13 04:42 UTC, artursouza approved these changes

2023-06-13 04:42 UTC, merged